[phases.build]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd backend && python manage.py collectstatic --noinput",
    "cd backend && python manage.py migrate"
]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[start]
cmd = "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
